version: "3.8"

services:
  db:
    image: postgres:17.2-alpine3.21
    container_name: leadsoft.DB
    restart: always
    environment:
      POSTGRES_USER: leadsoft
      POSTGRES_PASSWORD: leadsoft
      POSTGRES_DB: leadsoftdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: leadsoft.API
    depends_on:
      - db
    environment:
      ConnectionStrings__PostgreSQL: "Host=db;Port=5432;Database=leadsoftdb;Username=leadsoft;Password=leadsoft"
    ports:
      - "8080:8080"
      - "8081:8081"
    entrypoint: ["/bin/sh", "-c", "dotnet-ef database update && dotnet LeadSoft.Test.dll"]

volumes:
  pgdata: