version: "3.8"

services:
  db:
    image: postgres:17.2-alpine3.21
    container_name: leadsoft.DB
    restart: always
    environment:
      POSTGRES_USER: leadsoft
      POSTGRES_PASSWORD: leadsoft
      POSTGRES_DB: leadsoftdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - leadsoft-net

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: leadsoft.API
    depends_on:
      - db
    environment:
      ASPNETCORE_URLS: "http://0.0.0.0:8080;http://0.0.0.0:8081"
      ConnectionStrings__PostgreSQL: "Host=db;Port=5432;Database=leadsoftdb;Username=leadsoft;Password=leadsoft"
      ALLOWED_ORIGINS: "http://localhost:64461,http://localhost:64462,http://localhost:64463, http://leadsoft.FRONT/64461"
      CONNECTION_STRING: "Host=db;Port=5432;Database=leadsoftdb;Username=leadsoft;Password=leadsoft"
    ports:
      - "8080:8080"
      - "8081:8081"
    entrypoint: ["/bin/sh", "-c", "dotnet LeadSoft.Test.dll"]
    networks:
      - leadsoft-net

  front:
    build:
      context: ../LeadSoft.Test.App
      dockerfile: Dockerfile
    container_name: leadsoft.FRONT
    environment:
      VITE_APP_API_URL: "http://localhost:8080/api"
      VITE_APP_WSS_URL: "http://localhost:8080/ProcessListener"
    ports:
      - "64461:64461"
    command: ["npm", "run", "dev"]
    networks:
      - leadsoft-net

volumes:
  pgdata:

networks:
  leadsoft-net:
    driver: bridge